{{- if .Values.monstache.enabled }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: "{{ template "bk-cmdb.fullname" . }}-monstache"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    component: monstache
spec:
  replicas: {{ .Values.monstache.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      component: monstache
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        component: monstache
        values-hash: "{{ toYaml .Values | sha256sum | trunc 63 }}"
      {{- if or .Values.monstache.annotations .Values.monstache.podAnnotations .Values.global.cni.calico.ipv4pools }}
      annotations:
        {{- with .Values.monstache.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.monstache.podAnnotations }}
          {{- toYaml .Values.monstache.podAnnotations | nindent 8 }}
        {{- end }}
        {{- include "common.cni.calicoIpv4Pools" (dict "global" .Values.global $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "common.images.pullSecrets" (dict "global" .Values.global) | nindent 6 }}
      containers:
      - name: monstache
        image: {{ .Values.image.registry }}/{{ .Values.monstache.image.repository }}:{{ .Values.monstache.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        workingDir: {{ .Values.monstache.workDir }}
        command: ["./monstache"]
        args: ["-f", "./etc/config.toml"]
        ports:
        - containerPort: {{ .Values.monstache.port }}
        volumeMounts:
          - name: configures
            mountPath: {{ .Values.monstache.configDir }}

        {{- if .Values.monstache.resources }}
        resources: {{ toYaml .Values.monstache.resources | nindent 10 }}
        {{- end }}
      volumes:
        - name: configures
          configMap:
            name: {{ .Release.Name }}-monstache-configures

{{- end }}
